#ifndef DNSHEADER_FLAGS_H
#define DNSHEADER_FLAGS_H
#include <iothdns.h>

#define FLAGS_EPERM(X) (IOTHDNS_RESPONSE | (X & IOTHDNS_RD) | IOTHDNS_RCODE_EPERM)
#define FLAGS_ENOENT(X) (IOTHDNS_RESPONSE | IOTHDNS_AA | \
    (X & IOTHDNS_RD) | IOTHDNS_RCODE_ENOENT)
#define FLAGS_OK(X) (IOTHDNS_RESPONSE | (X & IOTHDNS_RD) | \
    IOTHDNS_RA | IOTHDNS_RCODE_OK)
#define FLAGS_OK_AA(X) (FLAGS_OK(X) | IOTHDNS_AA)
#define FLAGS_TRUNC(X) (FLAGS_OK(X) | IOTHDNS_TRUNC)

#endif
